name: deploy hetzner

on:
  push:
    branches: [ hetzner ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./setup/amazon-cloudwatch-agent.json ./.platform/nginx/nginx.conf"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/root"
        SCRIPT_AFTER: |
          sudo apt install nginx certbot nginx-extras -y
          cp -v nginx.conf /etc/nginx/nginx.conf
          service nginx restart
          wget https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
          sudo dpkg -i -E ./amazon-cloudwatch-agent.deb
          rm ./amazon-cloudwatch-agent.deb
          cp -v amazon-cloudwatch-agent.json /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
          mkdir -p ~/.aws
          sudo tee ~/.aws/credentials > /dev/null <<EOF
          [AmazonCloudWatchAgent]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          sudo systemctl enable amazon-cloudwatch-agent
          sudo systemctl start amazon-cloudwatch-agent          
          sudo systemctl status amazon-cloudwatch-agent
          echo $RSYNC_STDOUT

    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
    - run: |
        ./gradlew build -x checkstyleMain --no-daemon

    - name: Add env vars
      run: |
        echo "Environment=DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./setup/traccar.service
        echo "Environment=DOMAIN=${{ vars.DOMAIN }}" >> ./setup/traccar.service
        echo "Environment=EMAIL=${{ vars.EMAIL }}" >> ./setup/traccar.service
        echo "Environment=EVENT_FORWARD_URL=${{ vars.EVENT_FORWARD_URL }}" >> ./setup/traccar.service
        echo "Environment=FORWARD_URL=${{ vars.FORWARD_URL }}" >> ./setup/traccar.service
        echo "Environment=GEOCODER_TYPE=${{ vars.GEOCODER_TYPE }}" >> ./setup/traccar.service
        echo "Environment=GEOCODER_URL=${{ vars.GEOCODER_URL }}" >> ./setup/traccar.service
        echo "Environment=REDIS_HOST=${{ vars.REDIS_HOST }}" >> ./setup/traccar.service
        echo "Environment=LOGGER_CONSOLE=false" >> ./setup/traccar.service

    - name: Build installers
      working-directory: ./setup
      run: |
        sudo apt-get install makeself 
        wget -q https://corretto.aws/downloads/resources/11.0.25.9.1/amazon-corretto-11.0.25.9.1-linux-x64.tar.gz
        mkdir -p out/{conf,data,lib,logs,web,schema,templates,setup}
        cp -v ../target/tracker-server.jar out
        cp -v ../target/lib/* out/lib
        cp -v ../traccar.xml out/conf
        mkdir -p out/conf/setup
        cp -v default.xml out/conf/setup
        cp -v setup.sh traccar.service out
        tar -xf amazon-corretto-11.0.25.9.1-linux-x64.tar.gz
        echo "jlink"
        jlink --module-path jdk-*/jmods --add-modules java.se,jdk.charsets,jdk.crypto.ec,jdk.unsupported --output out/jre
        rm -rf jdk-*
        echo "makeself"
        makeself --needroot --quiet --notemp out traccar.run "traccar" ./setup.sh
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "setup/traccar.run"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SCRIPT_AFTER: |
          apt update
          apt install -y nginx certbot
          sudo /home/${{ secrets.REMOTE_USER }}/traccar.run
          sudo service traccar start
          echo $RSYNC_STDOUT
